bucket         = "6fc5w786-dev-terraform-states-bucket"
encrypt        = true
region         = "us-east-1"
dynamodb_table = "dev-terraform-lock-table"
key            = "distri-engine-api/terraform.tfstate"
