bucket         = "6fc5w786-stg-terraform-states-bucket"
encrypt        = true
region         = "us-east-1"
dynamodb_table = "stg-terraform-lock-table"
key            = "distri-engine-api/terraform.tfstate"
